In [1]:
import pandas as pd
import numpy as np
import sys

In [2]:
df = pd.read_csv('../sample_data/naruto.csv', encoding='ISO-8859-1')
df

Unnamed: 0  Num_episode  \
0             1            1   
1             2            2   
2             3            3   
3             4            4   
4             5            5   
..          ...          ...   
495         496          496   
496         497          497   
497         498          498   
498         499          499   
499         500          500   

                                                 Title                Type  \
0                                           Homecoming  Mixed Canon/Filler   
1                          The Akatsuki Makes Its Move  Mixed Canon/Filler   
2                              The Results of Training  Mixed Canon/Filler   
3                           The Jinchuriki of the Sand  Mixed Canon/Filler   
4                             The Kazekage Stands Tall  Mixed Canon/Filler   
..                                                 ...                 ...   
495  Hidden Leaf Story, the Perfect Day for a Weddi...         Manga Canon   
496  Hidden Leaf Story, the Perfect Day for a Weddi...         Manga Canon   
497  Hidden Leaf Story, the Perfect Day for a Weddi...         Manga Canon   
498  Hidden Leaf Story, the Perfect Day for a Weddi...         Manga Canon   
499  Hidden Leaf Story, the Perfect Day for a Weddi...         Manga Canon   

     Year_launch  Rate  Votes                Saga     Airdate  
0           2007   8.2    728  s1 Kazekage Rescue  2007-02-15  
1           2007   8.0    575  s1 Kazekage Rescue  2007-02-15  
2           2007   8.0    508  s1 Kazekage Rescue  2007-02-22  
3           2007   8.2    517  s1 Kazekage Rescue  2007-03-01  
4           2007   8.2    486  s1 Kazekage Rescue  2007-03-15  
..           ...   ...    ...                 ...         ...  
495         2017   7.5    313          s21 Series  2017-02-23  
496         2017   7.2    301          s21 Series  2017-03-02  
497         2017   6.8    305          s21 Series  2017-03-09  
498         2017   7.6    323          s21 Series  2017-03-16  
499         2017   8.8   1288          s21 Series  2017-03-23  

[500 rows x 9 columns]

In [3]:
df.head(10)

Unnamed: 0  Num_episode                                Title  \
0           1            1                           Homecoming   
1           2            2          The Akatsuki Makes Its Move   
2           3            3              The Results of Training   
3           4            4           The Jinchuriki of the Sand   
4           5            5             The Kazekage Stands Tall   
5           6            6                      Mission Cleared   
6           7            7                         Run, Kankuro   
7           8            8               Team Kakashi, Deployed   
8           9            9               The Jinchuriki's Tears   
9          10           10  Sealing Jutsu: Nine Phantom Dragons   

                 Type  Year_launch  Rate  Votes                Saga  \
0  Mixed Canon/Filler         2007   8.2    728  s1 Kazekage Rescue   
1  Mixed Canon/Filler         2007   8.0    575  s1 Kazekage Rescue   
2  Mixed Canon/Filler         2007   8.0    508  s1 Kazekage Rescue   
3  Mixed Canon/Filler         2007   8.2    517  s1 Kazekage Rescue   
4  Mixed Canon/Filler         2007   8.2    486  s1 Kazekage Rescue   
5  Mixed Canon/Filler         2007   8.2    480  s1 Kazekage Rescue   
6  Mixed Canon/Filler         2007   7.8    457  s1 Kazekage Rescue   
7  Mixed Canon/Filler         2007   7.7    437  s1 Kazekage Rescue   
8  Mixed Canon/Filler         2007   7.6    434  s1 Kazekage Rescue   
9  Mixed Canon/Filler         2007   7.5    424  s1 Kazekage Rescue   

      Airdate  
0  2007-02-15  
1  2007-02-15  
2  2007-02-22  
3  2007-03-01  
4  2007-03-15  
5  2007-03-29  
6  2007-03-29  
7  2007-04-12  
8  2007-04-12  
9  2007-04-19

In [4]:
df.tail(10)

Unnamed: 0  Num_episode  \
490         491          491   
491         492          492   
492         493          493   
493         494          494   
494         495          495   
495         496          496   
496         497          497   
497         498          498   
498         499          499   
499         500          500   

                                                 Title         Type  \
490  Shikamaru’s Story, a Cloud Drifting in the Sil...  Manga Canon   
491  Shikamaru’s Story, a Cloud Drifting in the Sil...  Manga Canon   
492  Shikamaru’s Story, a Cloud Drifting in the Sil...  Manga Canon   
493  Hidden Leaf Story, the Perfect Day for a Weddi...  Manga Canon   
494  Hidden Leaf Story, the Perfect Day for a Weddi...  Manga Canon   
495  Hidden Leaf Story, the Perfect Day for a Weddi...  Manga Canon   
496  Hidden Leaf Story, the Perfect Day for a Weddi...  Manga Canon   
497  Hidden Leaf Story, the Perfect Day for a Weddi...  Manga Canon   
498  Hidden Leaf Story, the Perfect Day for a Weddi...  Manga Canon   
499  Hidden Leaf Story, the Perfect Day for a Weddi...  Manga Canon   

     Year_launch  Rate  Votes        Saga     Airdate  
490         2017   7.1    290  s21 Series  2017-01-26  
491         2017   7.2    289  s21 Series  2017-02-02  
492         2017   7.4    298  s21 Series  2017-02-09  
493         2017   7.3    303  s21 Series  2017-02-16  
494         2017   6.7    313  s21 Series  2017-02-16  
495         2017   7.5    313  s21 Series  2017-02-23  
496         2017   7.2    301  s21 Series  2017-03-02  
497         2017   6.8    305  s21 Series  2017-03-09  
498         2017   7.6    323  s21 Series  2017-03-16  
499         2017   8.8   1288  s21 Series  2017-03-23

In [5]:
df.columns

Index(['Unnamed: 0', 'Num_episode', 'Title', 'Type', 'Year_launch', 'Rate',
       'Votes', 'Saga', 'Airdate'],
      dtype='object')

In [6]:
df.index

RangeIndex(start=0, stop=500, step=1)

In [7]:
df[['Title', 'Votes']]

Title  Votes
0                                           Homecoming    728
1                          The Akatsuki Makes Its Move    575
2                              The Results of Training    508
3                           The Jinchuriki of the Sand    517
4                             The Kazekage Stands Tall    486
..                                                 ...    ...
495  Hidden Leaf Story, the Perfect Day for a Weddi...    313
496  Hidden Leaf Story, the Perfect Day for a Weddi...    301
497  Hidden Leaf Story, the Perfect Day for a Weddi...    305
498  Hidden Leaf Story, the Perfect Day for a Weddi...    323
499  Hidden Leaf Story, the Perfect Day for a Weddi...   1288

[500 rows x 2 columns]

In [8]:
df.iloc[1:6]

Unnamed: 0  Num_episode                        Title                Type  \
1           2            2  The Akatsuki Makes Its Move  Mixed Canon/Filler   
2           3            3      The Results of Training  Mixed Canon/Filler   
3           4            4   The Jinchuriki of the Sand  Mixed Canon/Filler   
4           5            5     The Kazekage Stands Tall  Mixed Canon/Filler   
5           6            6              Mission Cleared  Mixed Canon/Filler   

   Year_launch  Rate  Votes                Saga     Airdate  
1         2007   8.0    575  s1 Kazekage Rescue  2007-02-15  
2         2007   8.0    508  s1 Kazekage Rescue  2007-02-22  
3         2007   8.2    517  s1 Kazekage Rescue  2007-03-01  
4         2007   8.2    486  s1 Kazekage Rescue  2007-03-15  
5         2007   8.2    480  s1 Kazekage Rescue  2007-03-29

In [9]:
df.loc[df['Type'] == 'Filler']

Unnamed: 0  Num_episode                 Title    Type  Year_launch  Rate  \
27           28           28  Beasts! Alive Again!  Filler         2007   7.1   
56           57           57       Robbed of Sleep  Filler         2008   6.9   
57           58           58            Loneliness  Filler         2008   6.6   
58           59           59           A New Enemy  Filler         2008   6.5   
59           60           60          Impermanence  Filler         2008   6.7   
..          ...          ...                   ...     ...          ...   ...   
467         468          468         The Successor  Filler         2016   8.2   
479         480          480     Naruto and Hinata  Filler         2016   7.4   
480         481          481     Sasuke and Sakura  Filler         2016   6.6   
481         482          482   Gaara and Shikamaru  Filler         2016   6.7   
482         483          483   Jiraiya and Kakashi  Filler         2016   6.8   

     Votes                                    Saga     Airdate  
27     367                      s1 Kazekage Rescue  2007-09-13  
56     269                s3 Twelve Guardian Ninja  2008-05-08  
57     267                s3 Twelve Guardian Ninja  2008-05-08  
58     262                s3 Twelve Guardian Ninja  2008-05-15  
59     256                s3 Twelve Guardian Ninja  2008-05-22  
..     ...                                     ...         ...  
467    255  s20 Infinite Tsukuyomi: The Invocation  2016-07-21  
479    309                              s21 Series  2016-10-20  
480    261                              s21 Series  2016-10-27  
481    261                              s21 Series  2016-11-03  
482    259                              s21 Series  2016-11-10  

[203 rows x 9 columns]

In [10]:
df.sort_values('Title')

Unnamed: 0  Num_episode                                      Title  \
461         462          462                          A Fabricated Past   
296         297          297           A Father's Hope, a Mother's Love   
383         384          384               A Heart Filled With Comrades   
317         318          318  A Hole in the Heart: the Other Jinchuriki   
12           13           13                     A Meeting With Destiny   
..          ...          ...                                        ...   
87           88           88                Wind Style: Rasen Shuriken!   
345         346          346                            World of Dreams   
471         472          472                              You Better...   
416         417          417                        You’ll Be My Backup   
114         115          115                             Zabuza's Blade   

                   Type  Year_launch  Rate  Votes  \
461  Mixed Canon/Filler         2016   8.2    270   
296         Manga Canon         2013   8.3    350   
383         Manga Canon         2014   8.2    506   
317              Filler         2013   6.2    187   
12   Mixed Canon/Filler         2007   8.1    432   
..                  ...          ...   ...    ...   
87          Manga Canon         2008   8.4    617   
345  Mixed Canon/Filler         2014   8.3    309   
471  Mixed Canon/Filler         2016   8.2    591   
416              Filler         2015   8.1    263   
114  Mixed Canon/Filler         2009   7.4    323   

                                                  Saga     Airdate  
461             s20 Infinite Tsukuyomi: The Invocation  2016-05-26  
296  s14 The Fourth Great Ninja War - Assailants Fr...  2013-01-24  
383  s18 The Fourth Great Ninja War - Obito Uchiha ...  2014-10-30  
317  s14 The Fourth Great Ninja War - Assailants Fr...  2013-06-20  
12                                  s1 Kazekage Rescue  2007-05-10  
..                                                 ...         ...  
87                             s4 Immortal Devastators  2008-12-11  
345  s15 The Fourth Great Ninja War - Sasuke And It...  2014-01-23  
471             s20 Infinite Tsukuyomi: The Invocation  2016-08-18  
416             s20 Infinite Tsukuyomi: The Invocation  2015-06-25  
114                          s6 Prophecy and Vengeance  2009-06-25  

[500 rows x 9 columns]

In [11]:
df.sort_values('Rate', ascending=False)

Unnamed: 0  Num_episode                                       Title  \
476         477          477                           Naruto and Sasuke   
132         133          133             The Tale of Jiraiya the Gallant   
374         375          375                           Kakashi vs. Obito   
475         476          476                            The Final Battle   
248         249          249                                   Thank You   
..          ...          ...                                         ...   
433         434          434                                Team Jiraiya   
448         449          449                           The Shinobi Unite   
312         313          313  Rain Followed by Snow, with Some Lightning   
375         376          376        The Directive to Take the Nine Tails   
376         377          377                     Naruto vs. Mecha Naruto   

            Type  Year_launch  Rate  Votes  \
476  Manga Canon         2016   9.5   2780   
132  Manga Canon         2009   9.5   2229   
374  Manga Canon         2014   9.3   1732   
475  Manga Canon         2016   9.3   1596   
248  Manga Canon         2012   9.3   1356   
..           ...          ...   ...    ...   
433       Filler         2015   5.1    198   
448       Filler         2016   5.1    203   
312       Filler         2013   5.1    206   
375       Filler         2014   4.6    260   
376       Filler         2014   4.2    348   

                                                  Saga     Airdate  
476             s20 Infinite Tsukuyomi: The Invocation  2016-09-29  
132                          s6 Prophecy and Vengeance  2009-10-29  
374  s18 The Fourth Great Ninja War - Obito Uchiha ...  2014-09-04  
475             s20 Infinite Tsukuyomi: The Invocation  2016-09-29  
248   s12 Nine-Tailed Fox Taming And Karmic Encounters  2012-02-09  
..                                                 ...         ...  
433             s20 Infinite Tsukuyomi: The Invocation  2015-10-15  
448             s20 Infinite Tsukuyomi: The Invocation  2016-02-18  
312  s14 The Fourth Great Ninja War - Assailants Fr...  2013-05-16  
375  s18 The Fourth Great Ninja War - Obito Uchiha ...  2014-09-11  
376  s18 The Fourth Great Ninja War - Obito Uchiha ...  2014-09-11  

[500 rows x 9 columns]

In [12]:
df = df[['Title', 'Votes']]
df.sort_values('Votes', ascending=False)

Title  Votes
476                Naruto and Sasuke   2780
132  The Tale of Jiraiya the Gallant   2229
374                Kakashi vs. Obito   1732
321                    Madara Uchiha   1600
475                 The Final Battle   1596
..                               ...    ...
410        The Targeted Tailed Beast    164
434                Order of Priority    164
438            The Child of Prophecy    164
404              The Imprisoned Pair    163
408                      Their Backs    163

[500 rows x 2 columns]

In [13]:
# df.to_csv('sample_data/naruto2.csv', index=False)

In [14]:
a = [1, 2, 3, 4, 5]
b = np.array([1, 2, 3, 4, 5])
a, b

([1, 2, 3, 4, 5], array([1, 2, 3, 4, 5]))

In [15]:
sys.getsizeof(a), b.nbytes

(104, 20)

In [16]:
d1 = np.array([1, 2, 3])
d1, d1.shape, d1.ndim, d1.dtype

(array([1, 2, 3]), (3,), 1, dtype('int32'))

In [17]:
d2 = np.array([[1, 2, 3], [4, 5, 6]])
d2, d2.shape, d2.ndim, d2.dtype

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3),
 2,
 dtype('int32'))

In [18]:
d3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
d3, d3.shape, d3.ndim, d3.dtype

(array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]),
 (2, 2, 2),
 3,
 dtype('int32'))

In [19]:
d4 = np.array([2, 3, 4])
result = np.add(d1, d4)
result

array([3, 5, 7])

In [20]:
d2[1,1] #item

5

In [21]:
d2[1,:] #linha

array([4, 5, 6])

In [22]:
d2[:, 2] #coluna

array([3, 6])